flist = {
    "scenario": "Fall17",
    "samples": [
        ['RunIIFall17MiniAODv2.TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8'],
        ['RunIIFall17MiniAODv2.TTZToQQ_TuneCP5_13TeV-amcatnlo-pythia8'],
        ['RunIIFall17MiniAODv2.TTWJetsToLNu_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8'],
        ['RunIIFall17MiniAODv2.TTWJetsToLNu_TuneCP5_PSweights_13TeV-amcatnloFXFX-madspin-pythia8'],
        ['RunIIFall17MiniAODv2.TTWJetsToQQ_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8'],
        ['RunIIFall17MiniAODv2.TTGJets_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8'],
        ['RunIIFall17MiniAODv2.TTGJets_TuneCP5_13TeV-amcatnloFXFX-madspin-pythia8_ext1'],
        ['RunIIFall17MiniAODv2.TTGamma_SingleLeptFromT_TuneCP5_PSweights_13TeV_madgraph_pythia8'],
        ['RunIIFall17MiniAODv2.TTGamma_SingleLeptFromTbar_TuneCP5_PSweights_13TeV_madgraph_pythia8'],
        ['RunIIFall17MiniAODv2.TTGamma_Dilept_TuneCP5_PSweights_13TeV_madgraph_pythia8'],
        ['RunIIFall17MiniAODv2.TTHH_TuneCP5_13TeV-madgraph-pythia8'],
        ['RunIIFall17MiniAODv2.TTTT_TuneCP5_PSweights_13TeV-amcatnlo-pythia8'],
        ['RunIIFall17MiniAODv2.TTTW_TuneCP5_13TeV-madgraph-pythia8'],
        ['RunIIFall17MiniAODv2.TTWH_TuneCP5_13TeV-madgraph-pythia8'],
        ['RunIIFall17MiniAODv2.TTWZ_TuneCP5_13TeV-madgraph-pythia8'],
        ['RunIIFall17MiniAODv2.TTZH_TuneCP5_13TeV-madgraph-pythia8'],
        ['RunIIFall17MiniAODv2.TTZZ_TuneCP5_13TeV-madgraph-pythia8'],
        ['RunIIFall17MiniAODv2.TTTJ_TuneCP5_13TeV-madgraph-pythia8'],
        ['RunIIFall17MiniAODv2.ttHJetToNonbb_M125_TuneCP5_13TeV_amcatnloFXFX_madspin_pythia8'],
        ['RunIIFall17MiniAODv2.ttHJetTobb_M125_TuneCP5_13TeV_amcatnloFXFX_madspin_pythia8'],
    ]
}
