flist = {
    "scenario": "Fall17",
    "samples": [
        ['Fall17.TTJets_TuneCP5_13TeV-madgraphMLM-pythia8'],
        ['Fall17.TTJets_SingleLeptFromT_TuneCP5_13TeV-madgraphMLM-pythia8'],
        ['Fall17.TTJets_SingleLeptFromTbar_TuneCP5_13TeV-madgraphMLM-pythia8'],
        ['Fall17.TTJets_DiLept_TuneCP5_13TeV-madgraphMLM-pythia8'],
        ['Fall17.TTJets_SingleLeptFromT_genMET-150_TuneCP5_13TeV-madgraphMLM-pythia8'],
        ['Fall17.TTJets_SingleLeptFromTbar_genMET-150_TuneCP5_13TeV-madgraphMLM-pythia8'],
        ['Fall17.TTJets_DiLept_genMET-150_TuneCP5_13TeV-madgraphMLM-pythia8'],
        ['Fall17.TTJets_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8'],
        ['Fall17.TTJets_HT-800to1200_TuneCP5_13TeV-madgraphMLM-pythia8'],
        ['Fall17.TTJets_HT-1200to2500_TuneCP5_13TeV-madgraphMLM-pythia8'],
        ['Fall17.TTJets_HT-2500toInf_TuneCP5_13TeV-madgraphMLM-pythia8'],
        ['Fall17.TTTo2L2Nu_TuneCP5_PSweights_13TeV-powheg-pythia8'],
        ['Fall17.TTToSemiLeptonic_TuneCP5_PSweights_13TeV-powheg-pythia8'],
        ['Fall17.TTToSemiLeptonic_TuneCP2_PSweights_13TeV-powheg-pythia8'],
        ['Fall17.TTToHadronic_TuneCP5_PSweights_13TeV-powheg-pythia8'],

        ['Fall17.TTTo2L2Nu_TuneCP5_erdON_13TeV-powheg-pythia8'],
        ['Fall17.TTTo2L2Nu_TuneCP5down_PSweights_13TeV-powheg-pythia8'], 
        ['Fall17.TTTo2L2Nu_TuneCP5up_PSweights_13TeV-powheg-pythia8'],
        ['Fall17.TTTo2L2Nu_hdampDOWN_TuneCP5_PSweights_13TeV-powheg-pythia8'], 
        ['Fall17.TTTo2L2Nu_hdampUP_TuneCP5_PSweights_13TeV-powheg-pythia8'],
        ['Fall17.TTToHadronic_TuneCP5_erdON_13TeV-powheg-pythia8'],
        ['Fall17.TTToHadronic_TuneCP5down_PSweights_13TeV-powheg-pythia8'], 
        ['Fall17.TTToHadronic_TuneCP5up_PSweights_13TeV-powheg-pythia8'], 
        ['Fall17.TTToHadronic_hdampDOWN_TuneCP5_PSweights_13TeV-powheg-pythia8'], 
        ['Fall17.TTToHadronic_hdampUP_TuneCP5_PSweights_13TeV-powheg-pythia8'], 
        ['Fall17.TTToSemiLeptonic_TuneCP5_erdON_13TeV-powheg-pythia8'], 
        ['Fall17.TTToSemiLeptonic_TuneCP5down_PSweights_13TeV-powheg-pythia8'], 
        ['Fall17.TTToSemiLeptonic_TuneCP5up_PSweights_13TeV-powheg-pythia8'], 
        ['Fall17.TTToSemiLeptonic_hdampDOWN_TuneCP5_PSweights_13TeV-powheg-pythia8'], 
        ['Fall17.TTToSemiLeptonic_hdampUP_TuneCP5_PSweights_13TeV-powheg-pythia8'], 
    ]
}
