import FWCore.ParameterSet.Config as cms

GoodJetsProducer = cms.EDFilter('GoodJetsProducer',
    TagMode = cms.bool(False),
    JetTag = cms.InputTag('slimmedJets'),
    maxJetEta = cms.double(5.0),
    minNconstituents = cms.int32(1),
    minNneutralsHE = cms.int32(2),
    minNneutralsHF = cms.int32(10),
    minNcharged = cms.int32(0),
    maxNeutralFraction = cms.double(0.99),
    maxNeutralFractionHE = cms.double(0.98),
    minNeutralFractionHF = cms.double(0.00),
    maxPhotonFraction = cms.double(0.99),
    minPhotonFractionHE = cms.double(0.01),
    maxPhotonFractionHE = cms.double(1.00),
    maxPhotonFractionHF = cms.double(0.90),
    minChargedFraction = cms.double(0.00),
    maxChargedEMFraction = cms.double(0.99),
    jetPtFilter = cms.double(30.),
    invertJetPtFilter = cms.bool(False),
    SaveAllJetsId = cms.bool(False),
    SaveAllJetsPt = cms.bool(False),
    ExcludeLepIsoTrackPhotons = cms.bool(False),
    JetConeSize = cms.double(0.04),
    SkipTag = cms.VInputTag()
)
