import FWCore.ParameterSet.Config as cms

jetproperties = cms.EDProducer('JetProperties',
    JetTag       = cms.InputTag('slimmedJets'),
    properties = cms.vstring(
        "chargedHadronMultiplicity",
        "neutralHadronMultiplicity",
        "electronMultiplicity"     ,
        "photonMultiplicity"       ,
        "muonMultiplicity"         ,
        "NumBhadrons"              ,
        "NumChadrons"              ,
        "chargedMultiplicity"      ,
        "neutralMultiplicity"      ,
        "partonFlavor"             ,
        "hadronFlavor"             ,
        "qgMult"                   ,
        "jetArea"                    ,
        "chargedHadronEnergyFraction",
        "neutralHadronEnergyFraction",
        "chargedEmEnergyFraction"    ,
        "neutralEmEnergyFraction"    ,
        "electronEnergyFraction"     ,
        "photonEnergyFraction"       ,
        "muonEnergyFraction"         ,
        "qgLikelihood"               ,
        "qgPtD"                      ,
        "qgAxis2"                    ,
        "bDiscriminatorCSV"          ,
        "bDiscriminatorMVA"          ,
    ),
    bDiscriminatorCSV = cms.vstring('pfCombinedInclusiveSecondaryVertexV2BJetTags'),
    bDiscriminatorMVA = cms.vstring('pfCombinedMVABJetTags'),
    qgLikelihood = cms.vstring('QGTagger:qgLikelihood'),
    qgPtD = cms.vstring('QGTagger:ptD'),
    qgAxis2 = cms.vstring('QGTagger:axis2'),
    qgMult = cms.vstring('QGTagger:mult'),
)
