import FWCore.ParameterSet.Config as cms

jetproperties = cms.EDProducer('JetProperties',
    JetTag       = cms.InputTag('slimmedJets'),
    BTagInputTagCSV = cms.string('pfCombinedSecondaryVertexBJetTags'),
    BTagInputTagMVA = cms.string('pfCombinedMVABJetTags'),
    properties = cms.vstring(
        "chargedHadronMultiplicity",
        "neutralHadronMultiplicity",
        "electronMultiplicity"     ,
        "photonMultiplicity"       ,
        "muonMultiplicity"         ,
        "NumBhadrons"              ,
        "NumChadrons"              ,
        "chargedMultiplicity"      ,
        "neutralMultiplicity"      ,
        "partonFlavor"             ,
        "hadronFlavor"             ,
        "qgMult"                   ,
        "jetArea"                    ,
        "chargedHadronEnergyFraction",
        "neutralHadronEnergyFraction",
        "chargedEmEnergyFraction"    ,
        "neutralEmEnergyFraction"    ,
        "electronEnergyFraction"     ,
        "photonEnergyFraction"       ,
        "muonEnergyFraction"         ,
        "qgLikelihood"               ,
        "qgPtD"                      ,
        "qgAxis2"                    ,
        "bDiscriminatorCSV"          ,
        "bDiscriminatorMVA"          ,
    )    
)
